### ISSUE TITLE
Building with Visual Studio 2019 and Cuda 11.1 gives error

### ISSUE THREAD

**Issue by AbsoluteNoober** [MomoDeve/FluidSimulation#1]
Hello. First of all, I would like to say thank you for your project. 

Here is the deal. I've tried building your project on Visual Studio 2019 with CUDA v11.1. I've also installed SFML (D:\SFML-2.5.1) 64-bit.  Edited the vcxproj file (changed 10.2 to 11.1). But the building throws an error.

"Build started...
1>------ Build started: Project: CudaFluidSimulation, Configuration: Debug x64 ------
1>Compiling CUDA source file kernel.cu...
1>
1>D:\Cuda\FluidSimulation-master\CudaFluidSimulation>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -DSFML_STATIC -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc142.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\kernel.cu.obj "D:\Cuda\FluidSimulation-master\CudaFluidSimulation\kernel.cu"
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.targets(785,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"  -G   --keep-dir x64\Debug -maxrregcount=0  --machine 64 --compile -cudart static  -g   -DSFML_STATIC -DWIN32 -DWIN64 -D_DEBUG -D_CONSOLE -D_MBCS -Xcompiler "/EHsc /W3 /nologo /Od /Fdx64\Debug\vc142.pdb /FS /Zi /RTC1 /MDd " -o x64\Debug\kernel.cu.obj "D:\Cuda\FluidSimulation-master\CudaFluidSimulation\kernel.cu"" exited with code 1.
1>Done building project "CudaFluidSimulation.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped =========="

Could you give me some insight on the issue?

Thank you n advance.

Regards, AbsoluteNoober.

**Comment by MomoDeve** [comment]
Hi,
As a quick solution, try creating your own cuda application project in Visual Studio, then add source files from this repository and set up dependencies. It should work. 

I admit there are problems with project installation - I will try to identify & fix them in the near future

**Comment by AbsoluteNoober** [comment]
Thanks for the reply.

I tried it as you advised (created empty project, added two source files, set up necessary configurations (setting SFML's include and lib paths etc.). 
It still produces the same error code. Maybe I should downgrade my CUDA version to 10.2? Or maybe the VS version? My machine is win10 pro 64bit with nvidia geforce mx250 gpu (compute capability 6.1, driver version 456.81). The output looks like this:
`1>      Task "CudaCompile"
1>        cmd.exe /C "C:\Users\altan\AppData\Local\Temp\tmp51f10a89f52340c1872962a43b42b5e2.cmd"
1>        "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DSFML_STATIC -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS   /MD " -o x64\Release\kernel.cu.obj "D:\Cuda\MyCudaApplication2\kernel.cu"
1>
1>        D:\Cuda\MyCudaApplication2>"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DSFML_STATIC -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS   /MD " -o x64\Release\kernel.cu.obj "D:\Cuda\MyCudaApplication2\kernel.cu"
1>        ptxas fatal   : Unresolved extern function '_Z3powfi'
1>        kernel.cu
1>        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.targets(785,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DSFML_STATIC -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS   /MD " -o x64\Release\kernel.cu.obj "D:\Cuda\MyCudaApplication2\kernel.cu"" exited with code 255.
1>      Done executing task "CudaCompile" -- FAILED.
1>    Done building target "CudaBuildCore" in project "MyCudaApplication2.vcxproj" -- FAILED.
1>
1>    Done building project "MyCudaApplication2.vcxproj" -- FAILED.
1>  Done executing task "MSBuild" -- FAILED.
1>
1>Done building project "MyCudaApplication2.vcxproj" -- FAILED.
1>
1>Build FAILED.
1>
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\BuildCustomizations\CUDA 11.1.targets(785,9): error MSB3721: The command ""C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\nvcc.exe" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --use-local-env -ccbin "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64" -x cu   -I"D:\SFML-2.5.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include"     --keep-dir x64\Release -maxrregcount=0  --machine 64 --compile -cudart static     -DSFML_STATIC -DWIN64 -DNDEBUG -D_CONSOLE -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /O2 /Fdx64\Release\vc142.pdb /FS   /MD " -o x64\Release\kernel.cu.obj "D:\Cuda\MyCudaApplication2\kernel.cu"" exited with code 255.
1>    0 Warning(s)
1>    1 Error(s)
1>
1>Time Elapsed 00:00:01.96
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========`

(Ooh, sorry for the big messy bulk of error message)

I must say I am a complete newbie in CUDA, not to mention I have little experience with VS. Nevertheless it seems to be a cuda compilation error or something. 

Thank you in advance.

**Comment by MomoDeve** [comment]
You have some linkage problems with pow/powf function. You can try searching it in cuda code and replace it with alternatives (maybe pow for double?)

**Comment by AbsoluteNoober** [comment]
Oh, hey. Thanks for the hint. Yep, I've managed to compile and run the code. It was that "pow(radius,2)" function. Apparently there is no "pow(float, int)" version of the function in the libraries. So I've just changed it to "radius*radius", and whoala, everything worked just fine.
Thanks for your project. It's nice!

**Comment by MomoDeve** [comment]
Hope now it works correctly. Thanks for the feedback!
